Feat/vvs/visit service new (#325)
* Creation of a new Visits Service

* Removed redundant code and methods
Added some new methods
put it all in the controller
I also added comments

* Removed redundant code and methods
Added some new methods
put it all in the controller
I also added comments

Missing: test update, getByPractitionerIdAndMonth, deleteVisit,

* the service works entirely, the only thing missing is testing

* Started Testing but it doesn't work
Error: Error creating bean for: EmebededMongo

* Minor Changes

* Fixed good imports + gradle annotations

* fix import for thenReturn

* fix import

* Added all the testing for the controller except for insert and update (Insert and Update don't work)

* Added all the testing for the controller except for insert and update (Insert and Update don't work)

* The changes I put in the insert and update did nothing, I know what the error is but I have no damn clue how to fix it.

* Final Controller (without insert and update)

* Controller Unit Testing done, update and insert work now.

* Fixing build.gradle, and docker-compose.ym

* THIS IS BUSTED

* Fixing build.gradle, and docker-compose.yml

* minor fix in docker-compose.yml

* fixing for docker to build.  still has issues to fix

* branch to main

* have to add tests

* Not working

* Visit Service Completely Done

* This commit has all the stuff from main.
Visit service done with 97 jacoco ratio

* No More Conflicts

Co-authored-by: Mohamad <mohamad-salameh@hotmail.com>
Co-authored-by: Brandon84-alt <brandonlevis84@gmail.com>
Co-authored-by: Kam1st <kam.hatteea@hotmail.com>